# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
         database_users:
                    entity: { class: AppBundle:User, property: username }

    firewalls:
#        secured_area:

#                   # this firewall applies to all URLs
#                   pattern: ^/
#
#                   # but the firewall does not require login on every page
#                   # denying access is done in access_control or in your controllers
#                   anonymous: true

        main:
            anonymous: ~
            provider: database_users
            form_login:
                      login_path: /admin/login
                      check_path: /admin/login
                      failure_path: /
                      default_target_path: /
            logout:
                      path:   /logout
                      target: /

    access_control:
                # require ROLE_ADMIN for /admin* IS_AUTHENTICATED_FULLY
        - { path: ^/admin/dashbroad, roles: [ROLE_ADMIN,ROLE_TEACHER,ROLE_ADVISOR] }
        - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
