# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
     app.file_uploader:
            class: AppBundle\Controller\FileUploader
            arguments: ['%upload_directory%']
     app.twig_extension:
            class: AppBundle\Twig\AppExtension
            public: false
            tags:
                - { name: twig.extension }
            arguments:
                em: "@doctrine.orm.entity_manager"
#     serializer.method:
#            class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
#     serializer.encoder.json:
#            class: Symfony\Component\Serializer\Encoder\JsonEncoder
#     serializer:
#            class: Symfony\Component\Serializer\Serializer

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
